version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  eureka:
    build: eureka
    image: eureka
    ports:
      - "8761:8761"
  currency:
    build: currency
    image: currency
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - postgres
  weather:
    build: weather
    image: weather
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - postgres
  prediction:
    build: prediction
    image: prediction
    ports:
      - "8083:8083"
    depends_on:
      - eureka
      - currency
      - weather