version: '3'
services:
  eureka:
    build: eureka
    image: isaeva/eureka:hw4
    ports:
      - "8761:8761"
  currency:
    build: currency
    image: isaeva/currency:hw4
    ports:
      - "8081:8081"
    depends_on:
      - eureka
  weather:
    build: weather
    image: isaeva/weather:hw4
    ports:
      - "8082:8082"
    depends_on:
      - eureka
  prediction:
    build: prediction
    image: isaeva/prediction:hw4
    ports:
      - "8083:8083"
    depends_on:
      - eureka
      - currency
      - weather