apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weahter
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /weather
spec:
  rules:
    - http:
        paths:
          - path: /weather
            pathType: Exact
            backend:
              service:
                name: weather
                port:
                  number: 8082